drop table if exists moderation_retention_aggregates;
drop table if exists operator_alerts;
drop table if exists object_deletion_jobs;
drop table if exists evidence_verdict_events;
drop table if exists moderation_access_audits;
drop table if exists operator_roles;
drop index if exists moderation_cases_open_goal_unique;
drop index if exists moderation_cases_evidence_unique;
alter table evidence_uploads drop column if exists metadata_purged_at;
alter table evidence_uploads drop column if exists tombstone_expires_at;
alter table evidence_uploads drop column if exists bytes_deleted_at;
alter table evidence_uploads alter column sha256 set not null;
alter table evidence_uploads alter column object_key set not null;
alter table evidences drop column if exists resolved_at;
alter table moderation_cases drop column if exists legal_hold_expires_at;
alter table moderation_cases drop column if exists verdict;
alter table moderation_cases drop column if exists resolution_business_key;
alter table moderation_cases drop column if exists resolution_reason;
alter table moderation_cases drop column if exists resolved_at;
alter table moderation_cases drop column if exists review_due_at;
alter table moderation_cases drop column if exists claim_expires_at;
alter table moderation_cases drop column if exists claimed_by;
alter table moderation_cases drop column if exists report_reason_code;
alter table moderation_cases drop column if exists reporter_subject_key;
